apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: wgbgs1b9p-java-springboot
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-springboot:25edc7383d81dcfa7a28420bdd9297d2e5a8373f@sha256:6a953f235f2161994c40a4f5f833235988f3a55d82d9d81c5c8c7fa2c894520b
          name: container-image
